### ISSUE TITLE
Reflection

### ISSUE THREAD

**Issue by sean-m-mckay** [UBC-MDS/DSCI-532_2024_1_TBtracker#29]
Whoever implements a graph should include a writeup, but this task involves combining these, adding a section on what the dashboard does well, and ensuring we do not exceed the word limit. 

- In this section,
  your group should clearly document which parts of your proposal/sketch
  you have implemented in your dashboard so far
  and explain what is not yet implemented.
- For anything that you have done differently than in your proposal/sketch
  explain why (e.g. implementation difficulty, explanation for why the new approach is more effective, etc).
- It is important that you include what you are aware of is not working in your dashboard,
  so that your TAs can distinguish between features in development and bugs.
- You should also explain if you have intentionally deviated
  from any of the best practices that we learned in 531 regarding effective visualizations.
- Reflect on what you think your dashboard does well currently
  what its limitations are,
  and what are good potential future improvements and additions.
- This section should not be more than 500 words
  and be written to the file `reports/m2-reflection.md` in your GitHub repo.

**Comment by hbandukw** [comment]
Please let me know what you guys think!

_Implementation Overview_
Our dashboard's main page features a geospatial heatmap and a histogram, which align with our initial proposal. Users can toggle between 'Incidence' or 'Mortality' of TB for a selected year and scale ('absolute' or 'relative'). Clicking on a country in the heatmap navigates to a dedicated tab displaying country-specific TB trends through five visualizations: three line plots (TB Mortality and Incidence, TB Case Fatality Ratio, TB-HIV Coinfection), a demographic-specific barchart, and a piechart for incidence by risk factors.

_Deviations from Proposal_
We have slightly deviated from our original design in the following ways:
- The 'Year' selection was changed from a slider to a dropdown to avoid confusion about it being a single year versus a range.
- The method to transition to country-specific data was reconsidered for better user experience, opting for a separate tab rather than a pop-up replacement.

_Known Issues_
We have yet to implement confidence intervals on the line charts for country-specific trends, which is a priority for the next iteration. Additionally, we are aware of the need to enhance the dashboard's aesthetics.

_Limitations and Future Improvements_
Our dashboard excels in interactive data visualization and ease of use. However, it currently lacks the display of statistical uncertainties, such as confidence intervals, which is crucial for informed decision-making. For future iterations, we plan to include these statistical elements and explore more engaging and aesthetic visualization options to improve the overall user experience.

**Comment by sean-m-mckay** [comment]
One other deviation
- The layout was changed on the global tab to group shared options affecting both graphs on the left-hand side, rather than having them above and below the graphs. Additionally, the charts were moved on top of each other to better fill the remaining vertical space
