### ISSUE TITLE
Add cards

### ISSUE THREAD

**Issue by sandygross** [UBC-MDS/DSCI-532_2024_1_TBtracker#61]
- Global card with absolute/relative incidence/mortality; also show increase or decrease to the previous year. Similar to this example:
![CEF289BB-76D1-4738-9021-242C597D8879](https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/assets/113273819/b41559c1-d877-4d5e-97d8-1828f7d55e73)

- Country specific card: if you hover over a country; it shows absolute/relative incidence/mortality of this country; also show increase or decrease to the previous year of this country

**Comment by hbandukw** [comment]
Hi everyone, I added a card for global statistics instead of country-specific statistics - I think it might be better since it won't change around too much - please let me know if you agree:

- The card is overlapping with the histogram right now but since the histogram will be removed, I left it there.
- There are three statistics displayed: 
     - First value: absolute/relative incidence/mortality values based on toggles for the chosen year.
     - Second value: YoN (Year over Next): shows the percentage change of the first value compared to the next year. 
     - Third value: NoY (Next over Year): shows the percentage change of the first value compared to the previous year.
- The value is blue if the change is negative and red if positive (for second and third values)
- For years 2000 and 2022, since there are no previous and next years respectively, I added "data not available" in black (for second and third values).
- background colour is tentative

Please watch the demo to see what it looks like currently:

https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/assets/20444993/1ee97194-bd7f-4268-a7a6-e090a804f0fe

**Comment by hbandukw** [comment]
- change border of card
- add global stats: "incidence" e.g. for incidence
- size smaller
- position

**Comment by zywkloo** [comment]
Awesome!
